name: report
channels: # these will define where conda searches for the packages
  - conda-forge # conda-forge should basically always be in this list
  - defaults # defaults too, obviously
dependencies: # outline all of your packages here
  - pandoc=2.14.0.2
  - pandoc-crossref
  - livereload
  - libsass
